-- mysql
SELECT TITLE, B.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS
     , DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS "CREATED_DATE"
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID
AND B.CREATED_DATE >= '2022-10-01'
AND B.CREATED_DATE < '2022-11-01'
ORDER BY R.CREATED_DATE, TITLE