--oracle
SELECT TITLE, B.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS
     , TO_CHAR(R.CREATED_DATE, 'yyyy-MM-dd') AS "CREATED_DATE"
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID
AND B.CREATED_DATE >= DATE '2022-10-01'
AND B.CREATED_DATE < DATE '2022-11-01'
ORDER BY R.CREATED_DATE, TITLE