-- mysql
SELECT O.ANIMAL_ID AS ANIMAL_ID, O.ANIMAL_TYPE AS ANIMAL_TYPE, O.NAME AS NAME
FROM ANIMAL_OUTS AS O 
LEFT OUTER JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE SEX_UPON_OUTCOME IN ('Spayed Female', 'Neutered Male')
AND SEX_UPON_INTAKE IN ('Intact Female', 'Intact Male')
ORDER BY ANIMAL_ID ASC