-- mysql
SELECT 
    H.CAR_ID, ROUND(H.AVERAGE_DURATION, 1) AS AVERAGE_DURATION
FROM (
        SELECT 
              CAR_ID
            , AVG(DATEDIFF(END_DATE, START_DATE) + 1) AS AVERAGE_DURATION
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
     ) H
WHERE H.AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
;