-- mysql
SELECT MONTH
     , CAR_ID
     , RECORDS
FROM (
        SELECT MONTH(START_DATE) AS MONTH
             , CAR_ID
             , COUNT(*) AS RECORDS
             , SUM(COUNT(*)) OVER(PARTITION BY CAR_ID) AS TOTAL_RECORDS
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID, MONTH(START_DATE)
    ) H
WHERE TOTAL_RECORDS >= 5
ORDER BY 1, 2 DESC
;