-- mysql
SELECT MONTH(B.START_DATE) AS MONTH
     , A.CAR_ID
     , COUNT(*) RECORDS
FROM (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
     ) A
     , CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE A.CAR_ID = B.CAR_ID
AND B.START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
GROUP BY MONTH, A.CAR_ID
ORDER BY 1, 2 DESC
;