-- mysql
SELECT SUM(G.SCORE) AS SCORE
     , E.EMP_NO
     , E.EMP_NAME
     , E.POSITION
     , E.EMAIL
FROM HR_EMPLOYEES E, HR_GRADE G
WHERE E.EMP_NO = G.EMP_NO
GROUP BY EMP_NO, YEAR
ORDER BY 1 DESC
LIMIT 1