-- mysql
WITH FOOD_RANK AS (
    SELECT CATEGORY
         , PRODUCT_NAME
         , PRICE
         , RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_RANK
WHERE PRICE_RANK = 1
ORDER BY MAX_PRICE DESC