-- mysql
SELECT O.PRODUCT_ID
     , PRODUCT_NAME
     , TOTAL_AMOUNT * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN (
    SELECT PRODUCT_ID
         , SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
) O
ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
;