-- mysql
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II,
    (SELECT T.ITEM_ID 
     FROM ITEM_INFO I, ITEM_TREE T 
     WHERE I.ITEM_ID = T.PARENT_ITEM_ID
     AND I.RARITY = 'RARE') ID
WHERE II.ITEM_ID = ID.ITEM_ID
ORDER BY II.ITEM_ID DESC