-- mysql
SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS, 
    ROUND(
        COUNT(DISTINCT I.USER_ID) 
          / 
        (
            SELECT COUNT(*) 
            FROM USER_INFO 
            WHERE JOINED >= DATE('2021-01-01')
            AND I.JOINED < DATE('2022-01-01')
        ),
        1) AS PUCHASED_RATIO -- 문제에서 오타 PURCHASED_RATIO 
FROM ONLINE_SALE O
JOIN USER_INFO I
ON O.USER_ID = I.USER_ID
WHERE I.JOINED >= DATE('2021-01-01')
AND I.JOINED < DATE('2022-01-01')
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH