-- mysql
SELECT F.FLAVOR
FROM FIRST_HALF F 
JOIN (
    SELECT FLAVOR
         , SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J
ON J.FLAVOR = F.FLAVOR
ORDER BY J.JULY_ORDER + F.TOTAL_ORDER DESC
LIMIT 3