-- mysql
WITH REST_SEOUL AS (
    SELECT 
        REST_ID, 
        REST_NAME, 
        FOOD_TYPE, 
        FAVORITES, 
        ADDRESS 
    FROM REST_INFO 
    WHERE ADDRESS LIKE '서울%'
)

SELECT 
    S.REST_ID, 
    S.REST_NAME, 
    S.FOOD_TYPE, 
    S.FAVORITES, 
    S.ADDRESS, 
    R.SCORE
FROM REST_SEOUL S
JOIN (
    SELECT 
        REST_ID,
        ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    WHERE REST_ID IN (SELECT REST_ID FROM REST_SEOUL)
    GROUP BY REST_ID
) R
ON S.REST_ID = R.REST_ID 
ORDER BY R.SCORE DESC, S.FAVORITES DESC;