-- mysql
SELECT D.YEAR
     , D.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV
     , E.ID
FROM ECOLI_DATA E
LEFT JOIN 
    (SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE
          , YEAR(DIFFERENTIATION_DATE) AS YEAR
     FROM   ECOLI_DATA 
     GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) D
ON YEAR(E.DIFFERENTIATION_DATE) = D.YEAR
ORDER BY D.YEAR, D.MAX_SIZE - E.SIZE_OF_COLONY