-- 재귀로 LEVEL 구하기
WITH RECURSIVE ECOLI_LEVEL AS (
    SELECT  ID,
			PARENT_ID,
			1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT  E.ID,
			E.PARENT_ID,
			L.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_LEVEL L ON E.PARENT_ID = L.ID
)

SELECT  COUNT(L.ID) AS COUNT,
		L.GENERATION
FROM ECOLI_LEVEL L
LEFT JOIN ECOLI_DATA D ON L.ID = D.PARENT_ID
WHERE D.ID IS NULL -- 자식이 없는
GROUP BY GENERATION
ORDER BY GENERATION;