-- mysql
SELECT 
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    U.GENDER,
    COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE O, USER_INFO U
WHERE O.USER_ID = U.USER_ID
AND U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER