-- mysql
-- 결과가 1개더라
SELECT 
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN (
    SELECT 
        MEMBER_ID,
        MEMBER_NAME
    FROM MEMBER_PROFILE
    WHERE MEMBER_ID = (
        SELECT 
            MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(MEMBER_ID) DESC
        LIMIT 1
    )
) P
ON R.MEMBER_ID = P.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT