-- mysql
SELECT
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
    SELECT 
        MEMBER_ID
    FROM ( 
        SELECT
            MEMBER_ID,
            RANK() OVER (ORDER BY COUNT(*) DESC) AS RANK_REVIEW
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
    ) M
    WHERE RANK_REVIEW = 1
) RR
JOIN REST_REVIEW R
ON RR.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE P
ON RR.MEMBER_ID = P.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
