-- mysql
WITH TOP_REVIEWER AS (
    SELECT 
        MEMBER_ID
    FROM ( 
        SELECT
            MEMBER_ID,
            RANK() OVER (ORDER BY COUNT(*) DESC) AS RANK_REVIEW
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
    ) M
    WHERE RANK_REVIEW = 1
)

SELECT 
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM TOP_REVIEWER T
JOIN REST_REVIEW R
ON T.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE M
ON T.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT